---
title: "sankey-wealth-mob-vis"
author: "Abhraneel Sarma"
date: "1/8/2019"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyr)
library(purrr)
library(jsonlite)
library(networkD3)
```


```{r}
df.mr <- read.csv("1-mobility-rates.csv", header=TRUE)

df.mr %<>% 
  mutate(
    o = as.character(o),
    o = replace(o, o == "Lowest Quintile", "Quintile 1"),
    o = replace(o, o == "Highest Quintile", "Quintile 5"),
    d = as.character(d),
    d = replace(d, d == "Lowest Quintile", "Quintile 1"),
    d = replace(d, d == "Highest Quintile", "Quintile 5")
  )
  
head(df.mr)
```

```{r}
nodes.mr <- df.mr  %>%
  select(o, d, white) %>%
  rename(
    Parent = o,
    Child = d,
    race = white
  ) %>%
  gather(type, name, -race) %>%
  unique() %>%
  arrange(desc(type), name, race) %>%
  mutate(
    race = ifelse(race == "No", "Black", "White"),
    name = paste(name, sep = " "),
    node = seq.int(nrow(.))-1
  ) %>%
  select(node, name, race, type)  %>%
  mutate(
    name = replace(name, name == "Quintile 1", "bottom 20% wealth quantile"),
    name = replace(name, name == "Quintile 2", "60% - 80% wealth quantile"),
    name = replace(name, name == "Quintile 3", "40% - 60% wealth quantile"),
    name = replace(name, name == "Quintile 4", "20% - 40% wealth quantile"),
    name = replace(name, name == "Quintile 5", "top 20% wealth quantile")
  )

nodes.mr
```


```{r}
links.mr <- df.mr %>%
  select(o, d, white, prob) %>%
  rename(
    source = o,
    target = d,
    race = white,
    value = prob
  ) %>%
  arrange(source, target, race) %>%
  mutate(
    race = ifelse(race == "No", "Black", "White"),
    source = rep(rep(0:1, 5), 5) + rep(seq(0, 9, by = 2), each = 10),
    target = rep(seq(10, 19), 5),
    value = value*100
  ) %>%
  select(source, target, value)

links.mr
```


```{r}
write_json(links.mr, "links.json", pretty = TRUE)
write_json(nodes.mr, "nodes.json", pretty = TRUE)
```

```{r}
df.ws <- read.csv("2-wealth-structure.csv", header=TRUE)

df.ws %<>%
  mutate(
    o = as.character(o),
    o = replace(o, o == "Lowest Quintile", "Quintile 1"),
    o = replace(o, o == "Highest Quintile", "Quintile 5"),
    d = as.character(d),
    d = replace(d, d == "Lowest Quintile", "Quintile 1"),
    d = replace(d, d == "Highest Quintile", "Quintile 5")
  )

head(df.ws)
```


```{r}
nodes.ws <- df.ws %>%
  select(o, d, white) %>%
  rename(
    Parent = o,
    Child = d,
    race = white
  ) %>%
  gather(type, name, -race) %>%
  unique() %>%
  arrange(desc(type), name, race) %>%
  mutate(
    race = ifelse(race == "No", "Black", "White"),
    name = paste(name, sep = " "),
    node = seq.int(nrow(.))-1
  ) %>%
  select(node, name, race, type)  %>%
  mutate(
    name = replace(name, name == "Quintile 1", "bottom 20% wealth quantile"),
    name = replace(name, name == "Quintile 2", "60% - 80% wealth quantile"),
    name = replace(name, name == "Quintile 3", "40% - 60% wealth quantile"),
    name = replace(name, name == "Quintile 4", "20% - 40% wealth quantile"),
    name = replace(name, name == "Quintile 5", "top 20% wealth quantile")
  )

nodes.ws
```


```{r}
links.ws <- df.ws %>%
  select(o, d, white, n) %>%
  rename(
    source = o,
    target = d,
    race = white,
    value = n
  ) %>%
  arrange(source, target, race) %>%
  mutate(
    race = ifelse(race == "No", "Black", "White"),
    ssource = rep(rep(0:1, 5), 5) + rep(seq(0, 9, by = 2), each = 10),
    starget = rep(seq(10, 19), 5),
  ) %>%
  select(source, target, value, race)

links.ws
```


```{r}
write_json(links.ws, "links.json", pretty = TRUE)
write_json(nodes.ws, "nodes.json", pretty = TRUE)
```

